version: '3'
services:
  maltego-trx:
    image: maltego-trx:gunicorn
    container_name: maltego-trx
    build: .
    ports:
      - "8080"

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - maltego-trx
