name: 'Sonatype Jake'

on: [push]

jobs:
  security:

    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.11
    - name: Run jake from Sonatype
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 freeze > requirements.txt
        pip3 install jake
        jake ddt -r requirements.txt

