name: 'Sonatype Jake'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    

jobs:
  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8.x', '3.9.x', '3.10.x' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run jake from Sonatype
        run: |
          python -m pip install --upgrade pip setuptools
          pip3 install -r requirements.txt
          pip3 freeze > frozen.requirements.txt
          
          pip3 install jake
          jake ddt --whitelist jake-whitelist.json
